# Generated by Django 4.2.7 on 2023-11-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('reporter', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images')),
                ('date_reported', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
